# Generated by Django 4.2.9 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_room_new_messages_for_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_last_message',
            field=models.CharField(max_length=100),
        ),
    ]
