# Generated by Django 4.2.9 on 2024-04-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_carimages_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car_id',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
