# Generated by Django 4.2.9 on 2024-04-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_maintenance',
            field=models.CharField(max_length=20),
        ),
    ]
