# Generated by Django 4.2.9 on 2024-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Ratings Column', 'verbose_name_plural': 'Ratings My brother'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate_content',
            field=models.TextField(choices=[('active', 'Active'), ('archived', 'Archived')]),
        ),
    ]
