# Generated by Django 4.2.9 on 2024-04-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_rating_options_alter_rating_rate_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate_content',
            field=models.TextField(),
        ),
    ]
