# Generated by Django 4.2.9 on 2024-04-21 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_content', models.TextField()),
                ('rate_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateProduct', to=settings.AUTH_USER_MODEL)),
                ('rate_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateProductSender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
